type: Handler
api_version: core/v2
metadata:
  name: influxdb
  namespace: default
spec:
  command: sensu-influxdb-handler -d sensu
  env_vars:
  - INFLUXDB_ADDR=http://influxdb.default.svc.cluster.local:8086
  - INFLUXDB_USER=sensu
  - INFLUXDB_PASS=password
  filters:
  - has_metrics
  handlers: null
  runtime_assets: null
  timeout: 10
  type: pipe
