type: Handler
api_version: core/v2
metadata:
  name: influxdb
  namespace: default
spec:
  command: sensu-influxdb-handler -d sensu
  env_vars:
  - INFLUXDB_ADDR=http://127.0.0.1:8086
  filters:
  - has_metrics
  handlers: null
  runtime_assets:
  - influxdb-handler
  timeout: 10
  type: pipe
